account/urls.py
from django.conf.urls import patterns, include, url
from account import views

urlpatterns = patterns('',
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$',    views.login, name='login'),
    url(r'^logout/$',   'django.contrib.auth.views.logout', {'template_name': 'logout.html'},name='logout'),

    url(r'^password-reset/$',
        'django.contrib.auth.views.password_reset', 
        {'template_name': 'password-reset.html'},
        name='password_reset'
    ),
    url(r'^password-reset-done/$',
        'django.contrib.auth.views.password_reset_done',
        {'template_name': 'password-reset-done.html'},
        name='password_reset_done'
    ),
    url(r'^password-reset-confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
        views.password_reset_confirm,
        name='password_reset_confirm'
    ),
    url(r'^password-reset-complete/$',
        'django.contrib.auth.views.password_reset_complete',
        {'template_name': 'password-reset-complete.html'},
        name='password_reset_complete'
    ),

    url(r'^password-change/$',
        views.password_change,
        name='password_change'
    ),
    url(r'^password-change-done/$',
        'django.contrib.auth.views.password_change_done',
        {'template_name': 'password-change-done.html'},
        name='password_change_done'
    ),

    url(r'^profile/$',      views.info,     name='userinfo'),
    url(r'^profile/edit/$', views.editinfo, name='userinfo_edit'),

    url(r'^snslogin/(\w+)/$',views.sns_signin, name='sns_signin'),
    url(r'^snscallback/(\w+)/$',views.sns_callback, name='sns_callback'),

    url(r'^sns-notsupport/$',views.sns_notsupport, name='sns_notsupport'),

    # for test
    url(r'^snsreg-success/$',views.snsreg_success ),

)

akbquiz/urls.py
from django.conf.urls import patterns, include, url
# from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$','akbquiz.views.home', name='home'),
    url(r'^quiz/', include("quiz.urls")),
    url(r'^responser/', include("responser.urls")),
    url(r'^crawler/', include("crawler.urls")),
    url(r'^account/', include("account.urls")),
    url(r'^database/', include("memberinfo.urls")),
    #url(r'^charts/', include("election.urls")),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
) #+ staticfiles_urlpatterns()

quiz/urls.py
from django.conf.urls import patterns, include, url
from quiz import views

urlpatterns = patterns('',
    url(r'^$',views.quizgame, name="quizgame"),
    url(r'^collect/$',views.collect,name="quiz_collect"),
    url(r'^collect/query/$',views.query,name="quiz_query"),

    # APIs
    url(r'^api/getquiz/$',views.api_quiz_get,name="api_quiz_get"),
    url(r'^api/collect/$',views.api_quiz_submit,name="api_quiz_submit"),
    url(r'^api/comment/$',views.api_quiz_comment,name="api_quiz_comment"),
)

account/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

class UserProfile(models.Model):
    """docstring for UserProfile"""
    user = models.OneToOneField(User, unique=True)

    display_name = models.CharField(max_length=32)
    # timezone = models.CharField(max_length=32)
    # lang = models.CharField(max_length=12)
    avatar = models.URLField(blank=True)
    
    weibo_id = models.CharField(max_length=100, blank=True)
    weibo_info = models.TextField(blank=True)

    weixin_id = models.CharField(max_length=100, blank=True)
    weixin_info = models.TextField(blank=True)

    qq_id = models.CharField(max_length=100, blank=True)
    qq_info = models.TextField(blank=True)

    renren_id = models.CharField(max_length=100, blank=True)
    renren_info = models.TextField(blank=True)

    baidu_id = models.CharField(max_length=100, blank=True)
    baidu_info = models.TextField(blank=True)

    #job = models.CharField(max_length=32, blank=True)
    birthday = models.DateField(blank=True, null=True)
    class Meta:
        db_table = u'user_profile'

def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user = instance, display_name = instance.username);

post_save.connect(create_user_profile, sender=User)

account/forms.py
from django import forms
from django.contrib.auth import forms as authForms
from account.models import UserProfile
from django.utils.translation import ugettext, ugettext_lazy as _

class ProfileForm(forms.Form):
    weibo_id = forms.CharField(max_length=64, required=False)
    weixin_id = forms.CharField(max_length=64, required=False)
    qq_id = forms.CharField(max_length=64, required=False)
    renren_id = forms.CharField(max_length=64, required=False)
    job = forms.CharField(max_length=32, required=False)
    age = forms.IntegerField(required=False)

class UserRegForm(authForms.UserCreationForm):
    username = forms.RegexField(
        label=_("Username"), 
        max_length=30,
        widget=forms.TextInput(attrs={'class':'form-control','placeholder':_('Username')},),
        regex=r'^[\w.@+-]+$',
        help_text = _("Required. 30 characters or fewer. Letters, digits and "
                      "@/./+/-/_ only."),
        error_messages = {
            'invalid': _("This value may contain only letters, numbers and "
                         "@/./+/-/_ characters.")})
    password1 = forms.CharField(
        label=_("Password"),
        widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':_('Password')},),)

    password2 = forms.CharField(
        label=_("Password confirmation"),
        widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':_('Type your password again'),}),
        help_text = _("Enter the same password as above, for verification."),)
class LoginForm(authForms.AuthenticationForm):
    username = forms.CharField(
        label=_("Username"), 
        max_length=30,
        widget=forms.TextInput(attrs={'class':'form-control','placeholder':_('Username')},),
        )
    password = forms.CharField(
        label=_("Password"), 
        widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':_('Password')},)
        )

class PasswordSetForm(authForms.SetPasswordForm):
    new_password1 = forms.CharField(
        label=_("New password"),
        widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':_("New password")},)
        )
    new_password2 = forms.CharField(
        label=_("New password confirmation"),
        widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':_("New password confirmation")},)
        )

class PasswordChangeForm(PasswordSetForm):
    error_messages = dict(PasswordSetForm.error_messages, **{
        'password_incorrect': _("Your old password was entered incorrectly. "
                                "Please enter it again."),
    })
    old_password = forms.CharField(label=_("Old password"),
        widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':_("Old password")},))

    def clean_old_password(self):
        """
        Validates that the old_password field is correct.
        """
        old_password = self.cleaned_data["old_password"]
        if not self.user.check_password(old_password):
            raise forms.ValidationError(
                self.error_messages['password_incorrect'])
        return old_password
PasswordChangeForm.base_fields.keyOrder = ['old_password', 'new_password1',
                                           'new_password2']
        

account/views.py
from django.shortcuts import get_object_or_404, render_to_response
from django.http import HttpResponseRedirect,HttpResponse
from django.core.urlresolvers import reverse
from django.template import RequestContext
from django.contrib.auth.decorators import login_required

@login_required
def info(request):
    profile = request.user.get_profile()
    return render_to_response('profile.html',profile);


@login_required
def editinfo(request):
    return HttpResponse();

def login(request):
    from account.forms import LoginForm
    from django.contrib.auth.views import login as login_
    return login_(request=request,template_name = 'login.html',authentication_form=LoginForm)
    pass

def register(request):
    from account.forms import UserRegForm
    if request.method == 'POST':
        form = UserRegForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            return HttpResponseRedirect(reverse('userinfo'))
    else:
        form = UserRegForm()
    return render_to_response("register.html", {'form': form,} ,context_instance = RequestContext(request))

def password_reset_confirm(request,uidb36,token):
    from account.forms import PasswordSetForm
    from django.contrib.auth.views import password_reset_confirm as _password_reset_confirm
    return _password_reset_confirm(request=request, uidb36=uidb36, token=token,
                           template_name='password-reset-confirm.html',
                           set_password_form=PasswordSetForm,)
    pass

def password_change(request):
    from account.forms import PasswordChangeForm
    from django.contrib.auth.views import password_change as _password_change
    return _password_change(request = request,template_name = 'password-change.html', password_change_form = PasswordChangeForm)
    pass

def sns_signin(request,sns):
    if sns == 'weibo':
        from TaskManager.weibo import APIError, APIClient
        client = APIClient()
        return HttpResponseRedirect(client.get_authorize_url())
    elif sns == 'qq':
        from TaskManager.qq import APIError, APIClient
        client = APIClient()
        return HttpResponseRedirect(client.get_authorize_url())
    elif sns == 'renren':
        from TaskManager.renren import APIError, APIClient
        client = APIClient()
        return HttpResponseRedirect(client.get_authorize_url())
    else:
        return HttpResponseRedirect(reverse('sns_notsupport'))

    pass

def sns_callback(request,sns):
    from account.models import UserProfile
    from account.utils import create_user, login_by_profile
    # get user info from sns site
    if sns == 'weibo':
        from TaskManager.weibo import APIError, APIClient

        code = request.GET.get('code')
        client = APIClient()
        tokendict = client.request_access_token(code)
        client.set_access_token(tokendict.access_token, tokendict.expires_in)

        sns_user = client.users.show.get(uid = tokendict.uid)

        userinfo = dict(
            uid = sns_user.id, \
            domain = sns_user.domain, \
            name = sns_user.name, \
            nickname = sns_user.screen_name, \
            avatar_url = sns_user.avatar_large or sns_user.profile_image_url, \
            homepage = 'http://weibo.com/%s' % sns_user.domain, \
            auth_token = tokendict.access_token, \
            expired_time = tokendict.expires_in)

        try:
            userProfile = UserProfile.objects.get(weibo_id = tokendict.uid)
        except UserProfile.DoesNotExist:
            content = create_user(request, userinfo, sns)
            return render_to_response("snsreg-success.html", content,context_instance = RequestContext(request))

        login_by_profile(request,userProfile)
        return HttpResponseRedirect(reverse('userinfo'))

    elif sns == 'qq':
        from TaskManager.qq import APIError, APIClient
        code = request.GET.get('code')
        client = APIClient()
        tokendict = client.request_access_token(code)
        r = client.request_openid(tokendict.access_token)
        tokendict.uid = r.openid
        client.set_access_token(tokendict.access_token, tokendict.uid, tokendict.expires_in)

        sns_user = client.user.get_info.get(openid = tokendict.uid)
        sns_user = sns_user.data

        userinfo = dict(
            uid = sns_user.openid , \
            name = sns_user.name, \
            nickname = sns_user.nick, \
            avatar_url = '%s/100'% (sns_user.head), \
            homepage = sns_user.homepage, \
            auth_token = tokendict.access_token, \
            expired_time = tokendict.expires_in)

        try:
            userProfile = UserProfile.objects.get(qq_id = tokendict.uid)
        except UserProfile.DoesNotExist:
            content = create_user(request, userinfo, sns)
            return render_to_response("snsreg-success.html", content, context_instance = RequestContext(request))

        login_by_profile(request, userProfile)
        return HttpResponseRedirect(reverse('userinfo'))

    elif sns == 'renren':
        from TaskManager.renren import APIError, APIClient
        from account.utils import multi_get_letter

        code = request.GET.get('code')
        client = APIClient()
        tokendict = client.request_access_token(code)
        sns_user = tokendict.user

        for avatar in sns_user.avatar:
            if avatar['type'] == 'large':
                avatar_url = avatar['url']
                break;
                pass
            pass
        userinfo = dict(
            uid = sns_user.id , \
            name = multi_get_letter(sns_user.name), \
            nickname = sns_user.name, \
            avatar_url = avatar_url, \
            homepage = 'http://www.renren.com', \
            auth_token = tokendict.access_token, \
            expired_time = tokendict.expires_in)

        try:
            userProfile = UserProfile.objects.get(renren_id = sns_user.id)
        except UserProfile.DoesNotExist:
            content = create_user(request, userinfo, sns)
            return render_to_response("snsreg-success.html", content,context_instance = RequestContext(request))

        login_by_profile(request, userProfile)
        return HttpResponseRedirect(reverse('userinfo'))
    else:
        return HttpResponseRedirect(reverse('sns_notsupport'))

    pass

def snsreg_success(request):
    content = {
        'username': 'CuGBabyBeaR-test', \
        'password': 'a-password-not-exist', \
        'snsname':'weibo', \
        'avatar_url':'http://tp4.sinaimg.cn/1450372003/180/5621738859/1', \
        'sns_url': 'http://weibo.com/%s' % 'duoz', \
        'snsusername':'CuGBabyBeaR', \
    }
    return render_to_response("snsreg-success.html", content,context_instance = RequestContext(request))

def sns_notsupport(request):
    return render_to_response("sns-notsupport.html", context_instance = RequestContext(request))
    pass



account/templates/login.html
{% extends "base.html" %}
{% load url from future %}
{% load i18n %}

{% block title %}{% trans "Log in" %}{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h3>{% trans "Log in" %}</h3>
      <p></p>
    </div>
  </div>

  {% if form.errors %}
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="alert alert-danger"><p>{% trans "Wrong Username and password combination." %}</p></div>
    </div>
  </div>
  {% endif %}
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <form class="form-horizontal" method="post" action="{% url 'login' %}" role="form">
        {% csrf_token %}
        <div class="form-group">
          <lable for="id_username" class="control-label col-md-3">{{form.username.label}}</lable>
          <div class="col-md-8">
            {{form.username}}
          </div>
        </div>
        <div class="form-group">
          <lable for="id_password" class="control-label col-md-3">{{form.password.label}}</lable>
          <div class="col-md-8">
            {{form.password}}
          </div>
        </div>
        <div class="form-group">
          <div class="col-md-4 col-md-offset-2">
            <button type="submit" class="btn btn-primary btn-block">{% trans "Log in" %}</button> 
          </div>
          <div class="col-md-4">
            <a href="/accounts/register" class="btn btn-default btn-block" role="button">{% trans "Sign up now" %}</a>
          </div>
          <div class="col-md-2">
              <p></p>
              <small><a href="/accounts/password-reset">{% trans "Forgot your password?" %}</a></small>
          </div>
        </div>
        <input type="hidden" name="next" value="{{ next }}" />
      </form>
      <h4>{% trans "Log in by sns account" %}</h4>
      <div class="row">
        <div class="col-md-3 col-md-offset-1">
          <a href="{% url 'sns_signin' 'weibo' %}"><img src="/static/image/weibo/login_24.png" alt=""/></a>
        </div>
        <div class="col-md-3">
          <a href="{% url 'sns_signin' 'qq' %}"><img src="/static/image/qq/login_24.png" alt=""/> </a>
        </div>
        <div class="col-md-3">
          <a href="{% url 'sns_signin' 'renren' %}"><img src="/static/image/renren/28.png" alt="" height="25" /> </a>
        </div>
        <!--
        <div class="col-md-3">
          <img src="/static/image/baidu/login-long.png" alt=""/> 
        </div>-->
      </div>
    </div>
  </div>
{% endblock %}

account/templates/logout.html
{% extends "base.html" %}
{% load url from future %}
{% load i18n %}

{% block title %}{% trans "Sign out" %}{% endblock %}

{% block css %}
<meta http-equiv="refresh" content="5;url=/">
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-md-10 col-md-offset-1">
  	<p></p>
    <div class="jumbotron">
      <h2>{% trans "Already logout" %}</h2>
      <p>{% trans "Will go to home page automatically in 5s." %} <small>{% trans "If your browser does not respond" %} <a href="/">{% trans "click here" %}</a></small></p>
    </div>
    <p></p>
  </div>
</div>

{% endblock %}

account/templates/password-change-done.html
{% extends "base.html" %}
{% load i18n %}
{% load url from future %}

{% block title %}{% trans 'Password change successful' %}{% endblock %}

{% block content %}
<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <p></p>
  <div class="jumbotron">
    <h2>{% trans 'Password change successful' %}</h2>

    <p>{% trans 'Your password was changed.' %}</p>
    <p></p>
  </div></div>
  <p></p>
</div>
{% endblock %}

account/templates/password-change.html
{% extends "base.html" %}
{% load i18n static %}
{% load url from future %}

{% block title %}{% trans 'Password change' %}{% endblock %}

{% block content %}
<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <h2>{% trans 'Password change' %}</h2>

    <p>{% trans "Please enter your old password, for security's sake, and then enter your new password twice so we can verify you typed it in correctly." %}</p>
    <p></p>
    <form class="form-horizontal"  action="" method="post" role="form">{% csrf_token %}
    <div class="form-group">
        {{ form.old_password.errors }}
        <label for="id_old_password" class="control-label col-md-3">{% trans 'Old password' %}:</label>
        <div class="col-md-5">{{ form.old_password }}</div>
        <div class="col-md-4">
          {% if form.old_password.errors %}
          <div class="alert alert-danger alert-inform"><small> {{ form.old_password.errors.as_text }}</small></div>
          {% endif%}
        </div>
    </div>

    <div class="form-group">
        {{ form.new_password1.errors }}
        <label for="id_new_password1" class="control-label col-md-3">{% trans 'New password' %}:</label>
        <div class="col-md-5">{{ form.new_password1 }}</div>
        <div class="col-md-4">
          {% if form.new_password1.errors %}
          <div class="alert alert-danger alert-inform"><small> {{ form.new_password1.errors.as_text }}</small></div>
          {% endif%}
        </div>
    </div>

    <div class="form-group">
    {{ form.new_password2.errors }}
        <label for="id_new_password2" class="control-label col-md-3">{% trans 'Password (again)' %}:</label>
        <div class="col-md-5">{{ form.new_password2 }}</div>
        <div class="col-md-4">
          {% if form.new_password2.errors %}
          <div class="alert alert-danger alert-inform"><small> {{ form.new_password2.errors.as_text }}</small></div>
          {% endif%}
        </div>
    </div>

    <div class="form-group">
      <div class="col-md-4 col-md-offset-2">
        <button type="submit" class="btn btn-primary btn-block">{% trans 'Change my password' %}</button> 
      </div>
    </div>

    <script type="text/javascript">document.getElementById("id_old_password").focus();</script>
  </form>
</div>
</div>

{% endblock %}

account/templates/password-reset-complete.html
{% extends "base.html" %}
{% load i18n %}
{% load url from future %}

{% block title %}{% trans 'Password reset complete' %}{% endblock %}

{% block content %}
<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <div class="jumbotron">
    <h2>{% trans 'Password reset complete' %}</h2>
    <p>{% trans "Your password has been set.  You may go ahead and log in now." %}</p>
    <p><a href="{% url 'login' %}">{% trans 'Log in' %}</a></p>
    <p></p>
  </div></div>
</div>
{% endblock %}

account/templates/password-reset-confirm.html
{% extends "base.html" %}
{% load i18n %}
{% load url from future %}

{% block title %}{% trans 'Password reset' %}{% endblock %}

{% block content %}

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    {% if validlink %}

    <h3>{% trans 'Enter new password' %}</h3>

    <p>{% trans "Please enter your new password twice so we can verify you typed it in correctly." %}</p>

    <form class="form-horizontal" action="" method="post" role="form">{% csrf_token %}

    <div class="form-group">
      <label class="control-label col-md-3" for="id_new_password1">{% trans 'New password:' %}</label>
      <div class="col-md-5">{{ form.new_password1 }}</div>
      <div class="col-md-4">
        {% if form.new_password1.errors %}
        <div class="alert alert-danger alert-inform"><small> {{ form.new_password1.errors.as_text }}</small></div>
        {% endif %}
      </div>
    </div>
    <div class="form-group">
      <label class="control-label col-md-3" for="id_new_password2">{% trans 'Confirm password:' %}</label>
      <div class="col-md-5">{{ form.new_password2 }}</div>
      <div class="col-md-4">
        {% if form.new_password2.errors %}
        <div class="alert alert-danger alert-inform"><small> {{ form.new_password2.errors.as_text }}</small></div>
        {% endif %}
      </div>
    </div>

      <div class="form-group">
        <div class="col-md-4 col-md-offset-2">
          <button type="submit" class="btn btn-primary btn-block">{% trans "Reset your password" %}</button> 
        </div>
      </div>
    </form>

    {% else %}

    <h3>{% trans 'Password reset unsuccessful' %}</h3>

    <p>{% trans "The password reset link was invalid, possibly because it has already been used.  Please request a new password reset." %}</p>

    {% endif %}
  </div>
</div>
{% endblock %}

account/templates/password-reset-done.html
{% extends "base.html" %}
{% load i18n %}
{% load url from future %}

{% block title %}{% trans 'Password reset successful' %}{% endblock %}

{% block content %}
<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <div class="jumbotron">
    <h2>{% trans 'Password reset successful' %}</h2>

    <p>{% trans "We've e-mailed you instructions for setting your password to the e-mail address you submitted. You should be receiving it shortly." %}</p>
  </div></div>
</div>
{% endblock %}

account/templates/password-reset.html
{% extends "base.html" %}
{% load url from future %}
{% load i18n %}

{% block title %}{% trans "Password reset" %}{% endblock %}

{% block content %}
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h3>{% trans "Password reset" %}</h3>
    <p>{% trans "Forgotten your password? Enter your e-mail address below, and we'll e-mail instructions for setting a new one." %}</p>
  </div>
</div>


<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <p></p>
    <form class="form-horizontal" method="post" action="{% url 'password_reset' %}" role="form">
      {% csrf_token %}
      <div class="form-group">
        <lable for="id_email" class="control-label col-md-3">{{form.email.label}}</lable>
        <div class="col-md-5">
          <input id="id_email" class="form-control" type="text" name="email" maxlength="75" placeholder="{% trans 'Enter your e-mail address' %}"/>
        </div>
        <div class="col-md-4">
          {% if form.email.errors %}
          <div class="alert alert-danger alert-inform"><small> {{ form.email.errors.as_text }}</small></div>
          {% endif%}
        </div>
      </div>
      <div class="form-group">
        <div class="col-md-4 col-md-offset-2">
          <button type="submit" class="btn btn-primary btn-block">{% trans "Reset your password" %}</button> 
        </div>
      </div>
    </form>
    <p></p>
    <p></p>
  </div>
</div>
{% endblock %}

account/templates/profile.html
{% extends "base.html" %}
{% load url from future %}
{% load i18n %}

{% block title %}{% trans "Profile" %}{% endblock %}

{% block content %}
<div class="row">
  <div class="col-md-4">
    头像
    账号
    昵称
    邮箱

  </div>
  <div class="col-md-8">
    QQ
    weibo
    renren
    
  </div>
</div>
Profole of user : {{ user.username }}
{% endblock %}

account/templates/register.html
{% extends "base.html" %}
{% load url from future %}
{% load i18n %}

{% block title %}{% trans "Register" %}{% endblock %}

{% block content %}
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h3>{% trans "Register an account" %}</h3>
    <p></p>
  </div>
</div>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <p></p>
	<form class="form-horizontal" method="post" action="." role="form">
      {% csrf_token %}
      <div class="form-group">
      	<lable for="id_username" class="control-label col-md-3">{{form.username.label}}</lable>
      	<div class="col-md-5">
      	  {{form.username}}
      	</div>
      	<div class="col-md-4">
      	  {% if form.username.errors %}
          <div class="alert alert-danger alert-inform"><small> {{ form.username.errors.as_text }}</small></div>
          {% endif %}
      	</div>
      </div>
      <div class="form-group">
      	<lable for="id_password1" class="control-label col-md-3">{{form.password1.label}}</lable>
      	<div class="col-md-5">
      	  {{form.password1}}
      	</div>
      	<div class="col-md-4">
      	  {% if form.password1.errors %}
          <div class="alert alert-danger alert-inform"><small> {{ form.password1.errors.as_text }}</small></div>
          {% endif %}
      	</div>
      </div>
      <div class="form-group">
      	<lable for="id_password2" class="control-label col-md-3">{{form.password2.label}}</lable>
      	<div class="col-md-5">
      	  {{form.password2}}
      	</div>
      	<div class="col-md-4">
      	  {% if form.password2.errors %}
          <div class="alert alert-danger alert-inform"><small> {{ form.password2.errors.as_text }}</small></div>
          {% endif %}
      	</div>
      </div>
      <div class="form-group">
      	<div class="col-md-4 col-md-offset-3">
      		<button type="submit" class="btn btn-primary btn-block">{% trans "Create your account" %}</button> 
      	</div>
      </div>
      <input type="hidden" name="next" value="{{ next }}" />
    </form>
    <p></p>
  </div>
</div>
	


{% endblock %}

account/templates/sns-notsupport.html
sns-notsupport.html

account/templates/snsreg-success.html
{% extends "base.html" %}
{% load url from future %}
{% load i18n %}

{% block title %}{% trans "Register by SNS" %}{% endblock %}

{% block content %}
<div class="row">
    
    <div class="col-md-8 col-md-offset-2">
    <div class="well">
      <div class="col-md-10 col-md-offser-1">
        <h3>{% trans "Register accomplished" %}</h3>
      </div>
        <div class="row">
          <div class="col-md-5 col-md-offset-1">
              <p>{% trans "Your account is created." %}</p>
              <div class="row"><div class="col-md-10 col-md-offset-1">
                <dl>
                  <dt>{% trans "Username" %}</dt>
                  <dd>{{ username }}</dd>
                  <dt>{% trans "Password" %}</dt>
                  <dd>{{ password }}</dd>
                </dl>
              </div></div>
              <p>{% trans "Please set your e-mail address in profile page and change your password asap." %}</p>
              <p><a href="{% url 'password_change' %}">{% trans "Change password" %}</a>*<small></p>
              <p>*{% trans "Password change needs your old password, please copy the password above." %}</small></p>
          </div>
          <div class="col-md-5">
              <h5>{% trans "This account created from SNS:" %} <strong>{{snsname}}</strong></h5>
              <p><a href="{{ sns_url }}"><img src="{{avatar_url}}" alt="{{ snsusername }}" class="img-thumbnail img-responsive"></a></p>
              <h4>{{ snsusername }}</h4>
          </div>
        </div>
    </div>
    </div>
</div>

{% endblock %}